# Site settings
# Personalize your site settings here

title: HakataYume # Replaces "Your awesome title"
email: yuhasmich@gmail.com # Optional, replace if you'd like
description: >-
  A digital scrapbook for Hakata memories. Here I share stories and photos
  from my time in Japan, including the memorable encounter with the monk
  at Shikaumi Shrine.
baseurl: "" # Keep as is for local development
url: "http://127.0.0.1:4000" # Base URL for local testing
twitter_username: "" # Optional, remove or replace
github_username: ""  # Optional, remove or replace

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# Add additional files or folders if needed
exclude:
  - dirtree.txt # Example: Exclude temporary files

